add column model
islam7x/crm pull request #10
Opened 2021-12-18 19:48 UTC by khaybulaev7

2021-12-19 11:16 UTC, andiskiy requested changes

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/categories_controller.rb
> +  before_action :set_column, only: %i[show]
у тебя же не одна колонка выбирается, а несколько, множественное число

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/categories_controller.rb
> +    @columns = Column.where(category_id: @category.id)
сделай через связи что ли, @category.columns

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/columns_controller.rb
> +    redirect_to category_path
че за ерунда вообще?

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/columns_controller.rb
> +    params.require(:column).permit(:name, :deleted_at)
deleted_at не нужен здесь

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/columns_controller.rb
> +    redirect_to category_path
и куда здесь редиректит?

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/columns_controller.rb
> +    @column.destroy
здесь есть поле `deleted_at`, поэтому обнови его текущим значением времени. `Time.current`.

2021-12-19 11:16 UTC, andiskiy commented on app/controllers/columns_controller.rb
> +  before_action :set_column, only: %i[ update edit destroy ]
ты здесь явно рубокопом не прошелся

2021-12-19 11:16 UTC, andiskiy commented on app/models/column.rb
> +  scope :column, -> { where('deleted_at < ?') }
зачем этот скоуп? тем более название как у модели и кривой

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/index.html.slim
> +      th
зачем ты их добавил в этом файле?

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/show.html.slim
> +  h1 Колонны
не колонны, а столбцы

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/show.html.slim
> +ul type='none'
зачем эти ul li здесь? я же просил убрать, ты не читаешь то что тебе пишут

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/show.html.slim
> +                p.btn.btn-success Активно
<img width="569" alt="Снимок экрана 2021-12-19 в 02 55 19" src="https://user-images.githubusercontent.com/17091892/146658660-1f37b640-93f8-421e-9593-70f202f154f3.png">

я просил вот так, а не как ты сам придумал и столбец просил назвать `Активный`

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/show.html.slim
> +                      method: :delete
че за кривая чанда? либо верни обратно, либо напиши правильно

2021-12-19 11:16 UTC, andiskiy commented on app/views/columns/edit.html.slim
> += simple_form_for @column, url: category_column_url do |f|
у тебя форма ничем не отличается от формы в new, но урлы отличаются, где-то передаешь @category, где-то нет. разберись и приведи в порядок свой код

2021-12-19 11:16 UTC, andiskiy commented on db/migrate/20211215133941_create_columns.rb
> +      t.integer  :category_id
`t.references :category`

2021-12-19 11:16 UTC, andiskiy commented on db/migrate/20211215133941_create_columns.rb
> +class CreateColumns < ActiveRecord::Migration[6.1]
нет рубокопа

2021-12-19 11:16 UTC, andiskiy commented on db/schema.rb
> -  enable_extension "plpgsql"
схему не нужно прогонять через рубокоп

2021-12-19 11:16 UTC, andiskiy commented on app/views/categories/show.html.slim
> +                p.btn.btn-secondary Неактивно
сделай вот как [тут](https://getbootstrap.com/docs/5.0/components/badge/#background-colors), там не `p` используется

2021-12-20 14:02 UTC, andiskiy requested changes

2021-12-20 14:02 UTC, andiskiy commented on app/models/column.rb
> +class Column < ApplicationRecord
нет рубокопа

2021-12-20 14:02 UTC, andiskiy commented on app/helpers/columns_helper.rb
> +module ColumnsHelper
нет рубокопа

2021-12-20 18:24 UTC, khaybulaev7 commented on db/migrate/20211215133941_create_columns.rb
> +class CreateColumns < ActiveRecord::Migration[6.1]
прогнал через рубокоп

2021-12-20 18:24 UTC, khaybulaev7 commented on app/models/column.rb
> +class Column < ApplicationRecord
прогнал через рубокоп

2021-12-20 18:24 UTC, khaybulaev7 commented on app/helpers/columns_helper.rb
> +module ColumnsHelper
прогнал через рубокоп

2021-12-20 18:29 UTC, khaybulaev7 commented on db/migrate/20211215133941_create_columns.rb
> +class CreateColumns < ActiveRecord::Migration[6.1]
<img width="1422" alt="Снимок экрана 2021-12-20 в 21 27 12" src="https://user-images.githubusercontent.com/92950976/146815285-be62c81a-2bbf-4d08-a722-0e8e9dc56210.png">

2021-12-20 18:30 UTC, khaybulaev7 commented on app/models/column.rb
> +class Column < ApplicationRecord
<img width="1440" alt="Снимок экрана 2021-12-20 в 21 29 26" src="https://user-images.githubusercontent.com/92950976/146815502-7464e76f-54ef-451f-bd26-452597efc96b.png">

2021-12-20 18:31 UTC, khaybulaev7 commented on app/helpers/columns_helper.rb
> +module ColumnsHelper
<img width="1440" alt="Снимок экрана 2021-12-20 в 21 30 47" src="https://user-images.githubusercontent.com/92950976/146815637-ac81bf8d-b096-4203-ac04-41275b441204.png">

2021-12-20 18:52 UTC, khaybulaev7 commented on db/schema.rb
> -  enable_extension "plpgsql"
<img width="833" alt="Снимок экрана 2021-12-20 в 21 45 54" src="https://user-images.githubusercontent.com/92950976/146817975-5971d4d1-665a-433d-bc8a-9af86a8fb38b.png">

2021-12-20 18:54 UTC, merged