add admin
islam7x/crm pull request #15
Opened 2022-01-01 17:18 UTC by khaybulaev7

2022-01-01 20:20 UTC, andiskiy requested changes

2022-01-01 20:20 UTC, andiskiy commented on app/controllers/admin/columns_controller.rb
> +  class Admin::ColumnsController < Admin::BaseController
и что за фигня?

2022-01-01 20:27 UTC, khaybulaev7 commented on app/controllers/admin/columns_controller.rb
> +  class Admin::ColumnsController < Admin::BaseController
<img width="1385" alt="Снимок экрана 2022-01-01 в 23 25 26" src="https://user-images.githubusercontent.com/92950976/147859563-a73f058f-045b-49c5-89a9-f53c5cdc53c2.png">

2022-01-01 20:27 UTC, khaybulaev7 commented on app/controllers/admin/columns_controller.rb
> +  class Admin::ColumnsController < Admin::BaseController
Исправил

2022-01-02 22:47 UTC, andiskiy requested changes

2022-01-02 22:47 UTC, andiskiy commented on app/controllers/admin/base_controller.rb
> +    #redirect_to(new_user_session_path) unless current_user.admin?
Я думал ты нормально в методе сделаешь. Так не делается вообще то. Для чего ты учил коллбеки

2022-01-03 20:04 UTC, merged