Item page
islam7x/crm pull request #17
Opened 2022-01-04 15:24 UTC by khaybulaev7

2022-01-04 16:17 UTC, andiskiy requested changes

2022-01-04 16:17 UTC, andiskiy commented on app/controllers/application_controller.rb
> +  #before_action :authenticate_user!
Зачем?

2022-01-04 16:17 UTC, andiskiy commented on app/controllers/admin/categories_controller.rb
> +    before_action :set_item, only: %i[show]
И зачем тут это?

2022-01-04 16:17 UTC, andiskiy commented on app/controllers/items_controller.rb
> +      @item.update(datetime_of_create: Time.current.to_formatted_s(:long))
Че за хуйня вообще?

2022-01-04 16:17 UTC, andiskiy commented on app/controllers/items_controller.rb
> +      redirect_to admin_category_path(@category)
Куда редиректит? Зачем на категорию?

2022-01-04 16:17 UTC, andiskiy commented on app/models/item.rb
> +  belongs_to :column, optional: true
Зачем ты это сделал? Оно же не для прикола туда добавлено

2022-01-04 16:17 UTC, andiskiy commented on app/views/admin/categories/show.html.slim
> +  h1 Товары
Я не просил добавлять сюда

2022-01-04 16:17 UTC, andiskiy commented on app/views/layouts/application.html.slim
> +                a.nav-link.active aria-current='page' href='/categories/:category_id/items' Товары
И че за чанда? Зачем ты делаешь то что от тебя не просили ?

2022-01-05 11:02 UTC, khaybulaev7 commented on app/controllers/application_controller.rb
> +  #before_action :authenticate_user!
авторизоваться просит

2022-01-05 13:39 UTC, andiskiy requested changes

2022-01-05 13:39 UTC, andiskiy commented on app/controllers/application_controller.rb
> +  #before_action :authenticate_user!
если просит - авторизуйся тогда, вот ты интересный. мы же для этого авторизацию сделали

2022-01-05 13:39 UTC, andiskiy commented on app/controllers/items_controller.rb
> +  def index
явно видно что рубокопом не прошелся

2022-01-05 13:39 UTC, andiskiy commented on app/controllers/items_controller.rb
> +  def set_column
я уже миллион раз говорил - методы должны описать то что в них делается, ты же не может назвать метод `киргизия` и там выбирать колонки? твой метод устанавливает одну колонку?

2022-01-05 13:39 UTC, andiskiy commented on app/views/items/new.html.slim
> +              input_html: { :value => DateTime.now.strftime("%d/%m/%Y  %H:%M "), class: 'form-control' },
`:value => ` старый синтаксис, еще двоеточия двойные, короче весь этот лейбл не правильный, не так должно быть

2022-01-05 13:39 UTC, andiskiy commented on app/views/items/new.html.slim
> +              collection: @columns.map{|column| [column.name, column.id]},
во первых, чтобы было везде одинаково `as: :select,` тоже должен перенести
во вторых, должен пройтись `slim-lint`'том здесь и в других файлах. Ты стабильно рубокоп и это продолжаешь игнорировать и писать говнокод

2022-01-05 13:39 UTC, andiskiy commented on app/views/layouts/application.html.slim
> +            ul.navbar-nav
что это значит?

2022-01-05 13:39 UTC, andiskiy commented on config/application.rb
> +    config.i18n.default_locale = :en
зачем это менять? я просил поменять, чтобы ты нормально читал ошибки, потому что ты русский перевод не сделал

2022-01-05 13:39 UTC, andiskiy commented on config/routes.rb
> +
всегда удивляет этот рандомный пробел или пустая строка. всегда не там где нужно. если и ставить ее, то перед root надо

2022-01-05 13:43 UTC, khaybulaev7 commented on app/views/layouts/application.html.slim
> +            ul.navbar-nav
На русском написал

2022-01-05 13:45 UTC, andiskiy commented on app/views/layouts/application.html.slim
> +            ul.navbar-nav
проверь правильность, если на русском пишут - меняют только текст `Categories`

2022-01-06 16:15 UTC, khaybulaev7 commented on app/controllers/items_controller.rb
> +  def index
![3E87A6B5-B8D5-4FF9-83A8-390DB02FE094](https://user-images.githubusercontent.com/92950976/148414050-63e44c8c-994d-443c-8493-090db28a8976.jpeg)

2022-01-06 19:11 UTC, andiskiy commented on app/controllers/items_controller.rb
> +  def index
Сделай пустую строку тогда. Зачем метод прилип к коллбеку?

2022-01-06 20:59 UTC, andiskiy requested changes

2022-01-06 20:59 UTC, andiskiy commented on app/views/items/new.html.slim
> +              collection: @columns.map{ |column| [column.name, column.id] },
Не прогнал через slim-lint

2022-01-06 20:59 UTC, andiskiy commented on config/locales/ru.yml
> +    day_names: [ Понедельник, Вторник, Среду, Четверг, Пятница, Суббота, Воскресенье ]
Лишний пробел после скобки. Для таких скобок пробел не ставится. Ставится для фигурных {}

2022-01-06 20:59 UTC, andiskiy commented on app/views/items/index.html.slim
> +          td = item.datetime_of_create
Отображение даты сформатируй и нормально покажи, через strftime

2022-01-06 20:59 UTC, andiskiy commented on app/views/items/edit.html.slim
> +              input_html: { value: DateTime.now.strftime('%d/%m/%Y  %H:%M'),
При отображении между датой и временем должно быть два пробела?

2022-01-07 19:31 UTC, andiskiy requested changes

2022-01-07 19:31 UTC, andiskiy commented on app/controllers/items_controller.rb
> +class ItemsController < ApplicationController
мы где-то обсуждали, что это должно быть в модуле categories, потому что роуты так построены

2022-01-07 19:31 UTC, andiskiy commented on app/views/admin/categories/show.html.slim
> +                                   class: 'btn btn-danger', method: :delete
зачем перенес? если переносишь - переноси нормально

2022-01-07 19:31 UTC, andiskiy commented on config/initializers/simple_form_bootstrap.rb
> +# frozen_string_literal: true
если ты этот добавил - старый удали

2022-01-07 20:00 UTC, andiskiy requested changes

2022-01-07 20:00 UTC, andiskiy commented on app/helpers/items_helper.rb
> +# frozen_string_literal: true
удали

2022-01-07 20:00 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +// Place all the styles related to the Items controller here.
удали

2022-01-07 21:40 UTC, merged