An item can only be deleted by an admin
islam7x/crm pull request #24
Opened 2022-01-30 21:43 UTC by khaybulaev7

2022-01-30 22:37 UTC, andiskiy requested changes
читай описание задачи

2022-01-30 22:37 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +  .fa-trash-alt {
я уже говорил, что не нужно использовать эти названия при переопределении аттрибутов ксс

2022-01-30 22:37 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +  .middle-icon-1 {
что за middle-icon-1, middle-icon-2 ? что это? средняя иконка 1, средняя иконка 2. как понять какая иконка это? первая, вторая..

2022-01-30 22:37 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +    position: absolute;
я тебе говорил что так делать не нужно и мы это обсуждали

2022-01-30 22:37 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +      .center-icon-2 {
это что за center-icon-2 center-icon-1?

2022-01-30 22:37 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +        flash.now[:danger] = I18n.t("controllers.categories.items.danger_messages", href:  edit_category_item_path(@category, @item)).html_safe
на рубокоп как всегда насрал

2022-01-30 22:37 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +          flash.now[:danger] = 'Заполните поля'
лишнее

2022-01-30 22:37 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      @item = Item.find_or_initialize_by(date_of_create: item_params[:date_of_create],
сюда включи и категорию тоже, ниже ненадо потом ее мерджить

2022-01-30 22:37 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +        @item.assign_attributes(item_params.merge(category_id: @category.id))
сделай чтобы даже если нашел эти аттибуты присоединились, чтобы в форме отображались то что ввели.

2022-01-30 22:37 UTC, andiskiy commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
вот кто тебя просил это убрать? и зачем ты это убрал? не нужно бежать и исправлять, напиши логическое объяснение

2022-01-30 22:37 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +          h.content_tag(:i, '', class: 'center-icon-2 fas fa-edit')
зачем вот это `''` писать тут и ниже?

2022-01-30 22:37 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +        h.concat(h.link_to(h.edit_category_item_path(category_id, id), class: ('center-icon-2 m-1')) do
что такое m-1?

2022-02-01 00:10 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
Эта часть была перенесена в метод div_block

2022-02-01 00:11 UTC, andiskiy commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
кто перенес? для чего эта штука?

2022-02-01 00:13 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> +          h.content_tag(:i, '', class: 'center-icon-2 fas fa-edit')
если не писать пустышку то будет такой результат
<img width="1417" alt="Снимок экрана 2022-02-01 в 03 11 40" src="https://user-images.githubusercontent.com/92950976/151893779-367ebfa8-fe7d-4d91-be40-6d11b97c217f.png">

2022-02-01 00:15 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +          h.content_tag(:i, '', class: 'center-icon-2 fas fa-edit')
`h.content_tag(:i, class: 'center-icon-2 fas fa-edit') {}` а так работает?

2022-02-01 00:15 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
Перенес я.  Она нужна для того чтобы если указано одно из значений оно все равно отображалось в таблице

2022-02-01 00:15 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> +        h.concat(h.link_to(h.edit_category_item_path(category_id, id), class: ('center-icon-2 m-1')) do
лишний класс забыл удалить

2022-02-01 00:16 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> +          h.content_tag(:i, '', class: 'center-icon-2 fas fa-edit')
да, поменял

2022-02-01 00:17 UTC, khaybulaev7 commented on app/assets/stylesheets/items.scss
> +      .center-icon-2 {
это классы который центрируют иконки(удалить, редактировать)

2022-02-01 00:17 UTC, andiskiy commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
а что значит все равно отображалось? сколько ячеек будет?

2022-02-01 00:21 UTC, khaybulaev7 commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
будет две ячейки только одна пустая

2022-02-01 00:23 UTC, andiskiy commented on app/decorators/item_decorator.rb
> -    if weight.blank? || quantity.blank?
а где такая задача была? для чего ты решил это поменять? давай самовольничать не будешь и будешь делать только то что в задаче описано

2022-02-01 01:03 UTC, andiskiy commented on app/assets/stylesheets/items.scss
> +      .center-icon-2 {
по-моему мы уже обсудили это. плюс названия кривые

2022-02-01 23:59 UTC, andiskiy requested changes

2022-02-01 23:59 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +        @item.save
сделал красиво, теперь понятнее стало, но надо еще красивее.
Мы уже смотрели ситуацию с валидацией. В таком случае товар не сохранится, но будет редирект.

Подсказка - флэш сообщение сделать только если запись не новая

2022-02-01 23:59 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +                                                             end
```suggestion
    h.content_tag(:td, quantity, class: 'left-td actions') + 
      h.content_tag(:td, weight, class: 'right-td actions') { div_block }
```

2022-02-01 23:59 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +                   end)
```suggestion
          h.concat(
            h.link_to(
              h.category_item_path(category_id, id),
              method: :delete,
              data: { confirm: 'Вы уверены?' }
            )  { h.content_tag(:i, class: 'items-icon-trash fas fa-trash-alt') {} }
          )
```

2022-02-01 23:59 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +               aria-label="Close"]
а slim-lint не нужон?

2022-02-02 21:08 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +               aria-label="Close"]
Здесь не ответил, не исправил

2022-02-02 21:12 UTC, khaybulaev7 commented on app/views/partials/_flash.html.slim
> +               aria-label="Close"]
<img width="1431" alt="Снимок экрана 2022-02-03 в 00 11 53" src="https://user-images.githubusercontent.com/92950976/152238191-5cd23556-2540-49cb-9cb1-f9f793664213.png">

2022-02-02 21:21 UTC, andiskiy requested changes

2022-02-02 21:21 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +                   end)
и здесь не ответил

2022-02-02 21:21 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +               aria-label="Close"]
двойные кавычки, я не знаю что ты там сделал

2022-02-03 15:26 UTC, andiskiy requested changes

2022-02-03 15:26 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +    before_action :item_exists?, only: %i[update]
зачем?

2022-02-04 13:55 UTC, andiskiy requested changes

2022-02-04 13:55 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
что будет если пользователь не админ?

2022-02-04 13:55 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if !item_exists?
попробуй обновить товар

2022-02-04 13:55 UTC, andiskiy commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
для чего это изменение сделано?

2022-02-04 13:55 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +      .alert.alert-dismissible class='alert-#{name}' role='alert'
и что теперь, флэш сообщение будет красным?

2022-02-04 13:57 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
не сможет удалить

2022-02-04 13:57 UTC, khaybulaev7 commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
""  кавычки не нужны же

2022-02-04 13:58 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
ты проверь что будет и напиши сюда

2022-02-04 13:59 UTC, andiskiy commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
а для чего нужны такие `""` и для чего такие `''`?

2022-02-05 12:57 UTC, khaybulaev7 commented on app/views/partials/_flash.html.slim
> +      .alert.alert-dismissible class='alert-#{name}' role='alert'
только ошибки

2022-02-05 12:58 UTC, khaybulaev7 commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
когда руби код нужны использовать  "" , в других случаях  ''

2022-02-05 12:59 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if !item_exists?
не обновляется, исправил

2022-02-05 12:59 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
<img width="1440" alt="Снимок экрана 2022-02-04 в 17 00 04" src="https://user-images.githubusercontent.com/92950976/152643126-7c6c1952-c597-4157-b828-73b5f262463c.png">

2022-02-05 12:59 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
просто будет редактирование товара

2022-02-05 13:00 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +    before_action :item_exists?, only: %i[update]
этот коллбэк не нужен там

2022-02-05 13:11 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
я не про это
покажи там кнопку и попробуй удалить

2022-02-05 13:11 UTC, andiskiy commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
и для чего ты тут исправил их?

2022-02-05 13:12 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +      .alert.alert-dismissible class='alert-#{name}' role='alert'
что только ошибки? в каком формате отображается ошибка? покажи

2022-02-05 13:16 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
<img width="1180" alt="Снимок экрана 2022-02-05 в 16 15 53" src="https://user-images.githubusercontent.com/92950976/152643667-d6b3d997-d8d8-4998-9fe2-5f06d07f2dd2.png">

2022-02-05 13:16 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
удаляет

2022-02-05 13:18 UTC, khaybulaev7 commented on app/views/partials/_flash.html.slim
> +      .alert.alert-dismissible class='alert-#{name}' role='alert'
<img width="1244" alt="Снимок экрана 2022-02-05 в 16 17 29" src="https://user-images.githubusercontent.com/92950976/152643712-b57462fa-4f97-43c8-a249-cf479d6fdd54.png">

2022-02-05 13:20 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
если удаляет, значит ты хуйню сделал.
я у тебя просил не в контроллере трогать, а показывать кнопку на фронте.
"покажи кнопку" - никак не означает, что надо лезть в контроллер. кнопка регулируется не в контроллере

2022-02-05 13:21 UTC, khaybulaev7 commented on app/views/categories/items/index.html.slim
> +                                    value='#{params[:from].presence || Date.current.beginning_of_month}']
щас исправлю

2022-02-05 13:22 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
удаляет если как админ зайти

2022-02-05 13:23 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
в задаче было написано запретить в контроллере , я поэтому написал

2022-02-05 13:24 UTC, andiskiy commented on app/views/partials/_flash.html.slim
> +      .alert.alert-dismissible class='alert-#{name}' role='alert'
https://github.com/islam7x/crm/pull/24#discussion_r799488381

2022-02-05 13:27 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
бля, причем тут админ???????????????
мы тестируем то что ты исправил. зачем ты верх дном все переворачиваешь? в задаче было запретить в контроллере, правильно сделал что в контроллере написал. то гавно что написал надо еще и тестировать, что ты правильно сделал, а не просто чанду делать и пытаться втюхивать это как на экзамене

2022-02-05 13:28 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
изначально речь шла про обычного пользователя. что будет если текущий пользователь не админ?
попросил для него показать кнопку и удалить товар, а ты не понятную и не логичную хуйню делаешь

2022-02-05 13:31 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
ну так не удаляет

2022-02-05 13:45 UTC, andiskiy commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
что происходит? белый экран?

2022-02-05 13:47 UTC, khaybulaev7 commented on app/controllers/categories/items_controller.rb
> +      if current_user.admin?
нет,  кнопка нажимается но ничего не происходит

2022-02-08 00:04 UTC, andiskiy requested changes

2022-02-08 00:04 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +    h.concat(quantity.presence && weight)
что отображает это выражение?

2022-02-08 00:04 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +    h.content_tag(:td, quantity, class: 'left-td actions') { div_block } +
мы вроде обсудили как это исправить, но ты как всегда хуйню сделал

2022-02-08 00:37 UTC, andiskiy requested changes

2022-02-08 00:37 UTC, andiskiy commented on app/decorators/item_decorator.rb
> +                                colspan: '2') do
либо верни обратно либо сделай нормально

2022-02-08 00:37 UTC, andiskiy commented on app/services/categories/columns/list_service.rb
> +            .select('columns.name, columns.position, sum(items.quantity) as sum_quantity, sum(items.weight) as sum_weight')
убери, ты не разобрался

2022-02-09 20:03 UTC, merged