сreated a separate section
islam7x/crm pull request #30
Opened 2022-03-01 06:25 UTC by khaybulaev7

2022-03-02 04:35 UTC, andiskiy requested changes

2022-03-02 04:35 UTC, andiskiy commented on app/assets/javascripts/application.js.coffee
> +    CRM.Parishes.init()
будет работать и без этого. потому что это реализовано ниже, на 25 строке

2022-03-02 04:35 UTC, andiskiy commented on app/assets/javascripts/components/parishes/parishes.js.coffee
> +    $('#search_parish').on 'click', @redirect
давай метод без собачки, если без собачки это как приватный, он нам не нужен из вне. и назови, наверное, `redirectTo`

2022-03-02 04:35 UTC, andiskiy commented on app/assets/javascripts/components/parishes/parishes.js.coffee
> +  @redirect: ->
тут тоже надо изменить, если без собачки - то пишется так
`redirect = ->`

2022-03-02 04:35 UTC, andiskiy commented on app/assets/stylesheets/expense.scss
> +  .actions {
этот код повторяется из items?
если да, то это надо в какой-то общий файл вынести. Не нужно повторять

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +    before_action :set_parish, only: %i[index new create edit update destroy]
если для всех - не обязательно писать `only`

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +
рубокоп и слим линт стабильно игнор

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +    def update_remainder
назови более понятно. это что? обновить остаток ? он же не обновляет, а возвращает остаток
`parish_remainder` можно, например

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +    def update_remainder
либо оставить это же название и обновлять уже в этом методе, это решение более правильное

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +      @expense = @parish.expenses.new(expense_params)
выбери из списка другой parish и попробуй создать, проверим создается ли

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +    @parishes = Parish.all
сделай сортировку по date_of_create. сначала самые новые и так по убыванию

2022-03-02 04:35 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +    if @parish.save
после создания remainder чему будет равно и что ты показываешь на странице?

2022-03-02 04:35 UTC, andiskiy commented on app/decorators/parish_decorator.rb
> +class ParishDecorator < ApplicationDecorator
пустые декораторы не нужно создавать

2022-03-02 04:35 UTC, andiskiy commented on app/helpers/expense_helper.rb
> +module ExpenseHelper
/

2022-03-02 04:35 UTC, andiskiy commented on app/services/categories/items/list_service.rb
> +        if category.columns.count == 0
для чего это? и почему рубокопом не проходишь?

2022-03-02 04:35 UTC, andiskiy commented on app/views/parishes/expenses/edit.html.slim
> +      = f.submit 'Изменить расход', class: 'btn btn-success'
напиши да просто "Обновить"

2022-03-02 04:35 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +      = link_to 'Создать расход', new_parish_expense_path, class: 'btn btn-primary'
просто Создать

2022-03-02 04:35 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +h5 Дата: #{ @parish.date_of_create }
слим линт по тебе плачет

2022-03-02 04:35 UTC, andiskiy commented on app/views/parishes/expenses/new.html.slim
> +    = f.input :killed, label:  'Убито:', input_html: { class: 'form-control' }
здесь и везде не убито, там скрине написано. напиши как там

2022-03-02 04:35 UTC, andiskiy commented on app/views/parishes/index.html.slim
> +            = @parishes.each do |parish|
для each равно не ставят

2022-03-02 13:45 UTC, khaybulaev7 commented on app/assets/stylesheets/expense.scss
> +  .actions {
у items для таблицы есть классы еще

2022-03-02 13:45 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +
прошелся

2022-03-02 14:07 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +      @expense = @parish.expenses.new(expense_params)
создает только присваивается к этому, а не к тому который был присвоен при создании, исправил

2022-03-02 14:33 UTC, khaybulaev7 commented on app/services/categories/items/list_service.rb
> +        if category.columns.count == 0
это если нет колонок то на ноль умножения не было

2022-03-02 14:33 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +    if @parish.save
ничему неравен

2022-03-02 14:33 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +    @parishes = Parish.all
сделал

2022-03-02 14:34 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +    def update_remainder
исправил

2022-03-02 14:34 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +    before_action :set_parish, only: %i[index new create edit update destroy]
исправил

2022-03-02 14:41 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +    if @parish.save
<img width="380" alt="image" src="https://user-images.githubusercontent.com/92950976/156383571-766aa77a-802d-47ed-9e0c-4e4cf41c1ce5.png">

2022-03-02 20:50 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +    if @parish.save
сделал

2022-03-03 14:01 UTC, andiskiy requested changes

2022-03-03 14:01 UTC, andiskiy commented on app/assets/stylesheets/expense.scss
> +  .actions {
ну и что? код же повторяется

2022-03-03 14:01 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +
не прошелся, он не оставляет пустые строки

2022-03-03 14:01 UTC, andiskiy commented on app/services/categories/items/list_service.rb
> +        if category.columns.count == 0
ты не проходишь рубокопом нихрена

2022-03-03 16:22 UTC, khaybulaev7 commented on app/services/categories/items/list_service.rb
> +        if category.columns.count == 0
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/92950976/156606671-00837ead-8b7e-45a7-9ef4-4be90dc11b3a.png">

2022-03-03 16:24 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +
<img width="979" alt="image" src="https://user-images.githubusercontent.com/92950976/156606962-123329a0-eabc-4caf-a9be-415e0aa6a66a.png">

2022-03-04 00:50 UTC, andiskiy requested changes

2022-03-04 00:50 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +    @parishes = Parish.all.order('date_of_create DESC')
`.order(date_of_create: :desc)`

2022-03-04 00:50 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +      redirect_to parishes_path
здесь тоже remainder надо изменить. но уже не как выше, а как в контроллере expenses

2022-03-04 00:50 UTC, andiskiy commented on app/helpers/expense_helper.rb
> +module ExpenseHelper
удали эти пустые файлы

2022-03-04 00:50 UTC, andiskiy commented on app/services/categories/items/list_service.rb
> +        end
```suggestion
        columns_count = category.columns.count
        return 1 if columns_count.zero?
         
        columns_count * 31

2022-03-04 00:50 UTC, andiskiy commented on test/controllers/expense_controller_test.rb
> +# frozen_string_literal: true
все эти лишние файлы удали

2022-03-05 13:05 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +      redirect_to parishes_path
сделал 959aac4ec6cc8d426f1905fa422db42ae0de953b

2022-03-09 05:45 UTC, andiskiy requested changes

2022-03-09 05:45 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +h5 = 'Дата: '  "#{@parish.date_of_create}"
```suggestion
h5 Дата: #{@parish.date_of_create}
```

2022-03-09 05:45 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +      @parish.update(remainder: @parish.quantity - (@expense.killed + @expense.sold_count))
здесь и в контроллере parishes, кажется, не правильно работает все.
Например:
количество 100
добавляешь два expense с killed 2 sold_count 2
у тебя в remainder будет 96. это же не остаток нихрена. а там должно быть 92. я описал образно что и как делать, а ты должен правильно это все считать и разбираться

2022-03-09 05:45 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +                                            parish_params[:quantity].to_i - (@parish.expenses.last.killed + @parish.expenses.last.sold_count)))
и вот это нормально сделай, что за длинная и кривая строка

2022-03-09 05:48 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +h5 Дата: #{ @parish.date_of_create }
если я говорю slim-lint плачет, почему ты только одну строку исправляешь? а то что ниже такое же Г это не нужно что ли исправлять?

2022-03-09 05:49 UTC, andiskiy commented on app/controllers/parishes/expenses_controller.rb
> +      @parish.update(remainder: @parish.quantity - (@expense.killed + @expense.sold_count))
и при удалении - ты удаляешь @expense, зачем по удаленной хрени считать тут что-то?

2022-03-09 05:52 UTC, andiskiy commented on app/controllers/parishes_controller.rb
> +    params.require(:parish).permit(:name, :quantity, :remainder, :date_of_create)
сюда remainder добавил, а на форму добавил? если нет зачем оно тут нужно?

2022-03-09 05:54 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +h5 = 'Дата: '  "#{@parish.date_of_create}"
если написал в одном месте исправить - исправлять должен другое Г, которое ниже тоже.

2022-03-09 18:27 UTC, khaybulaev7 commented on app/views/parishes/expenses/index.html.slim
> +h5 = 'Дата: '  "#{@parish.date_of_create}"
у меня так и было же

2022-03-09 18:33 UTC, khaybulaev7 commented on app/views/parishes/expenses/index.html.slim
> +h5 Дата: #{ @parish.date_of_create }
исправил 6dd3aab7f01048248abede711782b946d65e3a4d

2022-03-09 18:53 UTC, khaybulaev7 commented on app/controllers/parishes/expenses_controller.rb
> +      @parish.update(remainder: @parish.quantity - (@expense.killed + @expense.sold_count))
исправил 6dd3aab7f01048248abede711782b946d65e3a4d

2022-03-09 18:54 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +                                            parish_params[:quantity].to_i - (@parish.expenses.last.killed + @parish.expenses.last.sold_count)))
исправил 6dd3aab7f01048248abede711782b946d65e3a4d

2022-03-09 18:54 UTC, khaybulaev7 commented on app/controllers/parishes_controller.rb
> +    params.require(:parish).permit(:name, :quantity, :remainder, :date_of_create)
убрал 6dd3aab7f01048248abede711782b946d65e3a4d

2022-03-09 21:01 UTC, andiskiy requested changes

2022-03-09 21:01 UTC, andiskiy commented on app/views/parishes/expenses/index.html.slim
> +h5 Кол-во: #{ @parish.quantity }
Ну что за пробелы внутри скобок? Я же не должен на каждый символ указывать. Почему ты игнорируешь просьбы слим линт? Я 200 раз повторяю одно и тоже и миллион раз пропускаю тоже наверное

2022-03-12 20:13 UTC, merged